services:
  frontend:
    build:
      context: ./my-react-ts-app
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./my-node-backend
    ports:
      - "5000:5000"
    volumes:
      - ./my-node-backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
